# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Publish Package
permissions:
  id-token: write
# We need to do this differently:
on:
  workflow_run:
    workflows: ["Run Basic Tests"]
    types:
      - completed
jobs:
  check-status:
    name: Check Test and Lint Status
    runs-on: ubuntu-latest
    steps:
      name: Get Ref and Tag Info
      run: |
        echo "Ref: ${{ github.event.workflow_run.outputs.ref }}"
        echo "Is Tag: ${{ github.event.workflow_run.outputs.is_tag }}"
        if [[ "${{ github.event.workflow_run.outputs.is_tag }}" != "true" ]]; then
          echo "This is not a tag push. Aborting."
          exit 1
        fi
  build:
    runs-on: ubuntu-latest
    needs: check-status
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Build package
        run: |
          python -m build
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.9.0
