# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Publish Package
permissions:
  id-token: write
# We need to do this differently:
on:
  workflow_run:
    workflows: ["Run Basic Tests"]
    types:
      - completed
jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the event is a tag push
        id: check
        run: |
          echo "Triggered by ref: ${{ github.ref }}"
          if [[ "${GITHUB_REF}" =~ tags ]]; then
            echo "This is a tag push."
            echo "is_tag=true" >> $GITHUB_ENV
            echo "::set-output name=is_tag::true"
          else
            echo "This is NOT a tag push."
            echo "is_tag=false" >> $GITHUB_ENV
            echo "::set-output name=is_tag::false"
          fi
  check-status:
    runs-on: ubuntu-latest
    needs: check-tag
    if: needs.check-tag.outputs.is_tag == 'true'
    steps:
      - name: Get lint and test status
        run: |
          # [NOTE] This is just for debugging. You hopefully never get this far if lint or test fails.
          echo "Lint: ${{ github.event.workflow_run.outputs.lint_status }}"
          echo "Test: ${{ github.event.workflow_run.outputs.test_status }}"
  build:
    runs-on: ubuntu-latest
    needs: check-status
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Build package
        run: |
          python -m build
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.9.0
